const bradArray = [
  {
    className: 'aws',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAtoAAAGFAQMAAAD5EMbPAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAADpJREFUeNrtwTEBAAAAwqD1T20Hb6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE4DjVEAAeS/K3AAAAAASUVORK5CYII=',
  },

  {
    className: 'redux',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABkAAAAKUAQMAAABmImbOAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAJdJREFUeNrtwTEBAAAAwqD1T20Gf6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAzBlIAAdUcVn4AAAAASUVORK5CYII=',
  },
  {
    className: 'react',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABbwAAAHdAQMAAADsDy3hAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAGxJREFUeNrtwTEBAAAAwqD1T+1jDKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AZYxAAB/dRPrwAAAABJRU5ErkJggg==',
  },
  {
    className: 'cloudfare',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABLAAAAGZAQMAAACjdFrVAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAFNJREFUeNrtwTEBAAAAwqD1T20KP6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICzAfE/AAG8m6gwAAAAAElFTkSuQmCC',
  },
  {
    className: 'babel',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABLAAAAIhAQMAAABkBdFQAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAGZJREFUeNrtwQEBAAAAgiD/r25IQAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADArQFBhgABLTw6EQAAAABJRU5ErkJggg==',
  },

  {
    className: 'webpack',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAArwAAAEQAQMAAABoQjUIAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAC5JREFUeNrtwQENAAAAwqD3T20PBxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI8GXpAAAQ4N7WkAAAAASUVORK5CYII=',
  },
  {
    className: 'mongo-db',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlgAAACeAQMAAADUhuYfAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAACNJREFUeNrtwTEBAAAAwqD1T20ND6AAAAAAAAAAAAAAAODHAC7oAAGQ4ewPAAAAAElFTkSuQmCC',
  },
  {
    className: 'node-js',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlgAAAEsAQMAAAAl81/VAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAC1JREFUeNrtwTEBAAAAwqD1T20KP6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvgZZEAAB0O45vAAAAABJRU5ErkJggg==',
  },
  {
    className: 'gatsby',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAH0AQMAAACU5pVuAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAFRJREFUeNrtwTEBAAAAwqD1T20Gf6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgP2GAAB6sm75gAAAABJRU5ErkJggg==',
  },
  {
    className: 'graph-gl',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAFeAQMAAAAsYafmAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAEFJREFUeNrtwQEBAAAAgiD/r25IQAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCXAaxEAAGxpEIfAAAAAElFTkSuQmCC',
  },
  {
    className: 'mapbox',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAyAAAAC0AQMAAABWodrjAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAChJREFUeNrtwTEBAAAAwqD1T20MH6AAAAAAAAAAAAAAAAAAAAAAAOBjRwQAARH2T7IAAAAASUVORK5CYII=',
  },
  {
    className: 'serverless',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAArwAAAD3AQMAAADFdBWGAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAACxJREFUeNrtwTEBAAAAwqD1T20Hb6AAAAAAAAAAAAAAAAAAAAAAAAAAAAA4DFXfAAEHQsI0AAAAAElFTkSuQmCC',
  },
  {
    className: 'next',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlgAAACQAQMAAADujIdvAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAACFJREFUeNrtwTEBAAAAwqD1T20LL6AAAAAAAAAAAAAA4GcqwAAB+Pf6YQAAAABJRU5ErkJggg==',
  },

  {
    className: 'bootstrap',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAbUAAABzAQMAAAAlog6DAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAABxJREFUeNrtwQEBAAAAgiD/r25IQAEAAAAAAHwaGSgAAX5n76QAAAAASUVORK5CYII=',
  },

  {
    className: 'express',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAbMAAACdAQMAAAAE8gQ2AAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAB9JREFUeNrtwYEAAAAAw6D5Ux/gClUBAAAAAAAAAMAbIlgAAW9L410AAAAASUVORK5CYII=',
  },

  {
    className: 'nginx',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAArwAAADrAQMAAACxYNdmAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAACtJREFUeNrtwTEBAAAAwqD1T+1vBqAAAAAAAAAAAAAAAAAAAAAAAAAAADgDUbMAAZPPOeYAAAAASUVORK5CYII=',
  },

  {
    className: 'digital-ocean',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAC5AQMAAACBV4doAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAC1JREFUeNrtwTEBAAAAwqD1T20KP6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4GVbDgABhEkbVwAAAABJRU5ErkJggg==',
  },

  {
    className: 'socket-io',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAysAAAEiAQMAAADDCd/+AAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAADNJREFUeNrtwQENAAAAwqD3T20PBxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8GF0rgABpnm5ZAAAAABJRU5ErkJggg==',
  },
  {
    className: 'leaflet',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlgAAACfAQMAAAAf2jW6AAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAACJJREFUeNrtwQENAAAAwqD3T20PBxQAAAAAAAAAAAAAAHwaLzQAAdJD3X4AAAAASUVORK5CYII=',
  },

  {
    className: 'passport',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZgAAAB8AQMAAABuVzQ2AAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAABxJREFUeNrtwQEBAAAAgiD/r25IQAEAAAAAAHwbGTAAAVEyNNwAAAAASUVORK5CYII=',
  },
  {
    className: 'ubuntu',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQAQMAAAC6caSPAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAACpJREFUeNrtwTEBAAAAwqD1T+1vBqAAAAAAAAAAAAAAAAAAAAAAAAAAgDdPsAABlEEYXAAAAABJRU5ErkJggg==',
  },
]

export default bradArray

const vara = [
  {
    className: 'digital-ocean',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAC5AQMAAACBV4doAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAC1JREFUeNrtwTEBAAAAwqD1T20KP6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4GVbDgABhEkbVwAAAABJRU5ErkJggg==',
  },

  {
    className: 'socket-io',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAysAAAEiAQMAAADDCd/+AAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAADNJREFUeNrtwQENAAAAwqD3T20PBxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8GF0rgABpnm5ZAAAAABJRU5ErkJggg==',
  },

  {
    className: 'nginx',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAArwAAADrAQMAAACxYNdmAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAACtJREFUeNrtwTEBAAAAwqD1T+1vBqAAAAAAAAAAAAAAAAAAAAAAAAAAADgDUbMAAZPPOeYAAAAASUVORK5CYII=',
  },

  {
    className: 'leaflet',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlgAAACfAQMAAAAf2jW6AAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAACJJREFUeNrtwQENAAAAwqD3T20PBxQAAAAAAAAAAAAAAHwaLzQAAdJD3X4AAAAASUVORK5CYII=',
  },

  {
    className: 'passport',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZgAAAB8AQMAAABuVzQ2AAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAABxJREFUeNrtwQEBAAAAgiD/r25IQAEAAAAAAHwbGTAAAVEyNNwAAAAASUVORK5CYII=',
  },
  {
    className: 'ubuntu',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQAQMAAAC6caSPAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAACpJREFUeNrtwTEBAAAAwqD1T+1vBqAAAAAAAAAAAAAAAAAAAAAAAAAAgDdPsAABlEEYXAAAAABJRU5ErkJggg==',
  },
  {
    className: 'github',
    data:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoAQMAAABg5UFMAAAAA1BMVEX///+nxBvIAAAAAXRSTlMAQObYZgAAAB1JREFUeNrtwTEBAAAAwqD1T20LL6AAAAAAAAB4GBmYAAH/YcSlAAAAAElFTkSuQmCC',
  },
]
